/**
 * This code was generated by "react-native codegen-lib-harmony"
 */

#include "RNXlogJSIModule.h"
#include "mars/xlog/xloggerbase.h"
#include "XLogNativeLogger.h"
#include <jsi/jsi.h>
#include "mars/xlog/xlogger_interface.h"

namespace rnoh {
using namespace facebook;

int interceptAllReactNativeLog(jsi::Runtime &jsiRuntime)
{
    auto xlogAppenderFlush = jsi::Function::createFromHostFunction(jsiRuntime,
                                                                    jsi::PropNameID::forAscii(jsiRuntime, "xlogAppenderFlush"),
                                                                    1,
                                                                    [](jsi::Runtime &runtime, const jsi::Value &thisValue, const jsi::Value *arguments,
                                                                        size_t count) -> jsi::Value
                                                                    {
                                                                        if (count != 1) {
                                                                            throw jsi::JSError(runtime, "xlogAppenderFlush expects one argument (boolean isSync)!");
                                                                        }
                                                                        bool isSync = arguments[0].getBool();
                                                                        if (isSync) {
                                                                            mars::xlog::appender_flush_sync();
                                                                        } else {
                                                                            mars::xlog::appender_flush();
                                                                        }
                                                                        return jsi::Value(runtime, jsi::Value(1));
                                                                    });
    (jsiRuntime).global().setProperty(jsiRuntime, "xlogAppenderFlush", std::move(xlogAppenderFlush));
    return 1;
}

jsi::Value HostFunctionInstall(facebook::jsi::Runtime &rt, react::TurboModule &turboModule, const facebook::jsi::Value *args, size_t count)
{
    auto storageDirectory = args[0].asString(rt).utf8(rt);
    auto namePrefix = args[1].asString(rt).utf8(rt);
    int cacheDays = static_cast<int>(args[2].asNumber());
    bool isConsoleLogOpen = args[3].getBool();

#if DEBUG
    xlogger_SetLevel((TLogLevel)kLevelDebug);
#else
    xlogger_SetLevel((TLogLevel)kLevelInfo);
#endif
    mars::xlog::appender_set_console_log(isConsoleLogOpen);
    mars::xlog::XLogConfig config;
    config.mode_ = mars::xlog::kAppenderAsync;
    config.logdir_ = storageDirectory;
    config.nameprefix_ = namePrefix;
    config.pub_key_ = "";
    config.compress_mode_ = mars::xlog::kZlib;
    config.compress_level_ = 0;
    config.cachedir_ = "";
    config.cache_days_ = cacheDays;
    mars::xlog::appender_open(config);

    facebook::react::bindNativeLogger(rt, [](const std::string &message, unsigned int logLevel) {
        TLogLevel tLogLevel = kLevelAll;
        switch (logLevel) {
            case 0:
                tLogLevel = kLevelDebug;
                break;
            case 1:
                tLogLevel = kLevelInfo;
                break;
            case 2:
                tLogLevel = kLevelWarn;
                break;
            case 3:
                tLogLevel = kLevelError;
                break;
            default:
                tLogLevel = kLevelInfo;
                break;
            }

        XLoggerInfo info;
        info.level = tLogLevel;
        info.tag = "RN";
        info.filename = "";
        info.func_name = "";
        info.line = 0;
        gettimeofday(&info.timeval, NULL);
        info.pid = getpid();
        info.tid = gettid();
        info.maintid = gettid();
        xlogger_Write(&info, message.c_str());
    });

    interceptAllReactNativeLog(rt);
    return jsi::Value(true);
}

jsi::Value HostFunctionAppenderFlush(facebook::jsi::Runtime &rt, react::TurboModule &turboModule, const facebook::jsi::Value *args, size_t count)
{
    bool isSync = args[0].getBool();

    auto promiseConstructor = rt.global().getPropertyAsFunction(rt, "Promise");
    auto executor = jsi::Function::createFromHostFunction(
        rt,
        jsi::PropNameID::forAscii(rt, "executor"),
        2,
        [isSync](jsi::Runtime &runtime, const jsi::Value &thisValue, const jsi::Value *executorArgs, size_t executorCount) -> jsi::Value {
            auto resolve = executorArgs[0].asObject(runtime).asFunction(runtime);
            if (isSync) {
                mars::xlog::appender_flush_sync();
            } else {
                mars::xlog::appender_flush();
            }
            resolve.call(runtime, jsi::Value(true));
            return jsi::Value::undefined();
        });

    return promiseConstructor.callAsConstructor(rt, executor);
}

RNXlogJSIModule::RNXlogJSIModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name)
{
    methodMap_ = {
        {"install", MethodMetadata{4, HostFunctionInstall}},
        {"appenderFlush", MethodMetadata{1, HostFunctionAppenderFlush}},
    };
}

RNXlogJSIModule::~RNXlogJSIModule()
{
    mars::xlog::appender_close();
}
} // namespace rnoh
