/**
 * This code was generated by "react-native codegen-lib-harmony"
 */

#pragma once

#include "RNOH/ArkTSTurboModule.h"

namespace rnoh {

class JSI_EXPORT RNXlogJSIModule : public ArkTSTurboModule {
public:
    ~RNXlogJSIModule() override;
    RNXlogJSIModule(const ArkTSTurboModule::Context ctx, const std::string name);
};

} // namespace rnoh
